name: Build Barrington
on:
  push:
  pull_request:
jobs:
  barrington-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Prepare common workspace
        uses: qualcomm-zephyr/prepare_workspace@b520a53195a091b84ba2aad52c227371f715f296
